/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/auth/login": {
    /**
     * User login
     * @description Authenticate user and return JWT token
     */
    post: {
      requestBody: {
        content: {
          "application/json": {
            /**
             * Format: email
             * @example john.doe@example.com
             */
            email: string;
            /**
             * Format: password
             * @example SecureP@ss123
             */
            password: string;
          };
        };
      };
      responses: {
        /** @description Login successful */
        200: {
          content: {
            "application/json": {
              /**
               * @description JWT access token
               * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
               */
              accessToken?: string;
              /**
               * @description JWT refresh token
               * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
               */
              refreshToken?: string;
              user?: components["schemas"]["User"];
            };
          };
        };
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
      };
    };
  };
  "/auth/logout": {
    /**
     * User logout
     * @description Invalidate current JWT token
     */
    post: {
      responses: {
        /** @description Logout successful */
        204: {
          content: never;
        };
        401: components["responses"]["Unauthorized"];
      };
    };
  };
  "/auth/refresh": {
    /**
     * Refresh access token
     * @description Get new access token using refresh token
     */
    post: {
      requestBody: {
        content: {
          "application/json": {
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            refreshToken: string;
          };
        };
      };
      responses: {
        /** @description Token refreshed successfully */
        200: {
          content: {
            "application/json": {
              /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
              accessToken?: string;
            };
          };
        };
        401: components["responses"]["Unauthorized"];
      };
    };
  };
  "/users": {
    /**
     * List all users
     * @description Get paginated list of users with optional filtering
     */
    get: {
      parameters: {
        query?: {
          page?: components["parameters"]["PageParam"];
          pageSize?: components["parameters"]["PageSizeParam"];
          /** @description Filter by user role */
          role?: components["schemas"]["UserRole"];
          /** @description Filter by active status */
          isActive?: boolean;
        };
      };
      responses: {
        /** @description Users retrieved successfully */
        200: {
          content: {
            "application/json": components["schemas"]["UserListResponse"];
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
    /**
     * Create new user
     * @description Create a new user account (Admin only)
     */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateUserRequest"];
        };
      };
      responses: {
        /** @description User created successfully */
        201: {
          content: {
            "application/json": components["schemas"]["User"];
          };
        };
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        409: components["responses"]["Conflict"];
      };
    };
  };
  "/users/{userId}": {
    /**
     * Get user by ID
     * @description Retrieve specific user details
     */
    get: {
      parameters: {
        path: {
          /** @description User ID */
          userId: string;
        };
      };
      responses: {
        /** @description User retrieved successfully */
        200: {
          content: {
            "application/json": components["schemas"]["User"];
          };
        };
        401: components["responses"]["Unauthorized"];
        404: components["responses"]["NotFound"];
      };
    };
    /**
     * Delete user
     * @description Soft delete user account (Admin only)
     */
    delete: {
      parameters: {
        path: {
          userId: string;
        };
      };
      responses: {
        /** @description User deleted successfully */
        204: {
          content: never;
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
      };
    };
    /**
     * Update user
     * @description Update user details (Admin or self)
     */
    patch: {
      parameters: {
        path: {
          userId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateUserRequest"];
        };
      };
      responses: {
        /** @description User updated successfully */
        200: {
          content: {
            "application/json": components["schemas"]["User"];
          };
        };
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
      };
    };
  };
  "/schedules": {
    /**
     * List all schedules
     * @description Get paginated list of schedules with filtering
     */
    get: {
      parameters: {
        query?: {
          page?: components["parameters"]["PageParam"];
          pageSize?: components["parameters"]["PageSizeParam"];
          /** @description Filter by schedule status */
          status?: components["schemas"]["ScheduleStatus"];
          /** @description Filter by start date (from) */
          startDate?: string;
          /** @description Filter by end date (to) */
          endDate?: string;
        };
      };
      responses: {
        /** @description Schedules retrieved successfully */
        200: {
          content: {
            "application/json": components["schemas"]["ScheduleListResponse"];
          };
        };
        401: components["responses"]["Unauthorized"];
      };
    };
    /**
     * Create new schedule
     * @description Create a new training schedule (Manager/Admin only)
     */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateScheduleRequest"];
        };
      };
      responses: {
        /** @description Schedule created successfully */
        201: {
          content: {
            "application/json": components["schemas"]["Schedule"];
          };
        };
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
  };
  "/schedules/{scheduleId}": {
    /**
     * Get schedule by ID
     * @description Retrieve specific schedule details
     */
    get: {
      parameters: {
        path: {
          scheduleId: string;
        };
      };
      responses: {
        /** @description Schedule retrieved successfully */
        200: {
          content: {
            "application/json": components["schemas"]["Schedule"];
          };
        };
        401: components["responses"]["Unauthorized"];
        404: components["responses"]["NotFound"];
      };
    };
    /**
     * Delete schedule
     * @description Delete schedule (Admin only)
     */
    delete: {
      parameters: {
        path: {
          scheduleId: string;
        };
      };
      responses: {
        /** @description Schedule deleted successfully */
        204: {
          content: never;
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
      };
    };
    /**
     * Update schedule
     * @description Update schedule details (Manager/Admin only)
     */
    patch: {
      parameters: {
        path: {
          scheduleId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateScheduleRequest"];
        };
      };
      responses: {
        /** @description Schedule updated successfully */
        200: {
          content: {
            "application/json": components["schemas"]["Schedule"];
          };
        };
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
      };
    };
  };
  "/allocations": {
    /**
     * List all allocations
     * @description Get paginated list of trainer allocations
     */
    get: {
      parameters: {
        query?: {
          page?: components["parameters"]["PageParam"];
          pageSize?: components["parameters"]["PageSizeParam"];
          /** @description Filter by schedule ID */
          scheduleId?: string;
          /** @description Filter by trainer ID */
          trainerId?: string;
          /** @description Filter by allocation type */
          allocationType?: components["schemas"]["AllocationType"];
        };
      };
      responses: {
        /** @description Allocations retrieved successfully */
        200: {
          content: {
            "application/json": components["schemas"]["AllocationListResponse"];
          };
        };
        401: components["responses"]["Unauthorized"];
      };
    };
    /**
     * Create new allocation
     * @description Create trainer allocation (Manager/Admin only)
     */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateAllocationRequest"];
        };
      };
      responses: {
        /** @description Allocation created successfully */
        201: {
          content: {
            "application/json": components["schemas"]["TrainerAllocation"];
          };
        };
        400: components["responses"]["BadRequest"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        409: components["responses"]["Conflict"];
      };
    };
  };
  "/allocations/{allocationId}": {
    /** Get allocation by ID */
    get: {
      parameters: {
        path: {
          allocationId: string;
        };
      };
      responses: {
        /** @description Allocation retrieved successfully */
        200: {
          content: {
            "application/json": components["schemas"]["TrainerAllocation"];
          };
        };
        401: components["responses"]["Unauthorized"];
        404: components["responses"]["NotFound"];
      };
    };
    /** Delete allocation */
    delete: {
      parameters: {
        path: {
          allocationId: string;
        };
      };
      responses: {
        /** @description Allocation deleted successfully */
        204: {
          content: never;
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
      };
    };
  };
  "/audit-logs": {
    /**
     * List audit logs
     * @description Get paginated audit log entries (Admin only)
     */
    get: {
      parameters: {
        query?: {
          page?: components["parameters"]["PageParam"];
          pageSize?: components["parameters"]["PageSizeParam"];
          /** @description Filter by user ID */
          userId?: string;
          /** @description Filter by entity type */
          entityType?: string;
          /** @description Filter by action */
          action?: string;
        };
      };
      responses: {
        /** @description Audit logs retrieved successfully */
        200: {
          content: {
            "application/json": components["schemas"]["AuditLogListResponse"];
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * @description User role determining access permissions
     * @enum {string}
     */
    UserRole: "ADMIN" | "MANAGER" | "TRAINER" | "VIEWER";
    /**
     * @description Current status of a training schedule
     * @enum {string}
     */
    ScheduleStatus: "DRAFT" | "PUBLISHED" | "COMPLETED" | "CANCELLED";
    /**
     * @description Type of trainer allocation
     * @enum {string}
     */
    AllocationType: "ASSIGNED" | "REQUESTED" | "TENTATIVE";
    User: {
      /**
       * Format: uuid
       * @description Unique user identifier
       * @example 550e8400-e29b-41d4-a716-446655440000
       */
      id: string;
      /**
       * Format: email
       * @description User email address (unique)
       * @example john.doe@example.com
       */
      email: string;
      /**
       * @description User first name
       * @example John
       */
      firstName: string;
      /**
       * @description User last name
       * @example Doe
       */
      lastName: string;
      role: components["schemas"]["UserRole"];
      /**
       * @description Whether user account is active
       * @default true
       * @example true
       */
      isActive?: boolean;
      /**
       * Format: date-time
       * @description Account creation timestamp
       * @example "2024-01-15T10:30:00.000Z"
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description Last update timestamp
       * @example "2024-01-20T14:45:00.000Z"
       */
      updatedAt?: string;
    };
    Schedule: {
      /**
       * Format: uuid
       * @description Unique schedule identifier
       * @example 660e8400-e29b-41d4-a716-446655440001
       */
      id: string;
      /**
       * @description Schedule title
       * @example Q1 2024 Technical Training
       */
      title: string;
      /**
       * @description Detailed schedule description
       * @example Comprehensive technical training program for Q1 2024
       */
      description?: string;
      /**
       * Format: date
       * @description Schedule start date
       * @example "2024-01-15T00:00:00.000Z"
       */
      startDate: string;
      /**
       * Format: date
       * @description Schedule end date
       * @example "2024-03-31T00:00:00.000Z"
       */
      endDate: string;
      status: components["schemas"]["ScheduleStatus"];
      /**
       * Format: uuid
       * @description User ID who created the schedule
       * @example 550e8400-e29b-41d4-a716-446655440000
       */
      createdBy: string;
      /**
       * Format: date-time
       * @description Creation timestamp
       * @example "2024-01-10T09:00:00.000Z"
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description Last update timestamp
       * @example "2024-01-12T16:30:00.000Z"
       */
      updatedAt?: string;
    };
    TrainerAllocation: {
      /**
       * Format: uuid
       * @description Unique allocation identifier
       * @example 770e8400-e29b-41d4-a716-446655440002
       */
      id: string;
      /**
       * Format: uuid
       * @description Reference to schedule
       * @example 660e8400-e29b-41d4-a716-446655440001
       */
      scheduleId: string;
      /**
       * Format: uuid
       * @description Reference to trainer (user)
       * @example 550e8400-e29b-41d4-a716-446655440003
       */
      trainerId: string;
      allocationType: components["schemas"]["AllocationType"];
      /**
       * Format: date
       * @description Allocation start date
       * @example "2024-01-15T00:00:00.000Z"
       */
      startDate: string;
      /**
       * Format: date
       * @description Allocation end date
       * @example "2024-01-20T00:00:00.000Z"
       */
      endDate: string;
      /**
       * Format: float
       * @description Allocated hours per week
       * @example 40
       */
      hoursPerWeek?: number;
      /**
       * @description Additional allocation notes
       * @example Focus on advanced JavaScript topics
       */
      notes?: string;
      /**
       * Format: date-time
       * @description Creation timestamp
       * @example "2024-01-10T10:00:00.000Z"
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description Last update timestamp
       * @example "2024-01-11T14:20:00.000Z"
       */
      updatedAt?: string;
    };
    AuditLog: {
      /**
       * Format: uuid
       * @description Unique audit log identifier
       * @example 880e8400-e29b-41d4-a716-446655440003
       */
      id: string;
      /**
       * Format: uuid
       * @description User who performed the action
       * @example 550e8400-e29b-41d4-a716-446655440000
       */
      userId: string;
      /**
       * @description Action performed
       * @example UPDATE
       * @enum {string}
       */
      action: "CREATE" | "UPDATE" | "DELETE" | "LOGIN" | "LOGOUT";
      /**
       * @description Type of entity affected
       * @example Schedule
       */
      entityType: string;
      /**
       * Format: uuid
       * @description ID of affected entity
       * @example 660e8400-e29b-41d4-a716-446655440001
       */
      entityId: string;
      /**
       * @description JSON object with before/after values
       * @example {
       *   "status": {
       *     "before": "DRAFT",
       *     "after": "PUBLISHED"
       *   }
       * }
       */
      changes?: {
        [key: string]: unknown;
      };
      /**
       * Format: ipv4
       * @description IP address of request
       * @example 192.168.1.100
       */
      ipAddress?: string;
      /**
       * Format: date-time
       * @description When action occurred
       * @example "2024-01-12T16:30:00.000Z"
       */
      timestamp: string;
    };
    CreateUserRequest: {
      /**
       * Format: email
       * @example jane.smith@example.com
       */
      email: string;
      /** @example Jane */
      firstName: string;
      /** @example Smith */
      lastName: string;
      /**
       * Format: password
       * @description Password (min 8 chars, must include uppercase, lowercase, number, special char)
       * @example SecureP@ss123
       */
      password: string;
      role: components["schemas"]["UserRole"];
    };
    UpdateUserRequest: {
      firstName?: string;
      lastName?: string;
      role?: components["schemas"]["UserRole"];
      isActive?: boolean;
    };
    CreateScheduleRequest: {
      /** @example Q2 2024 Leadership Training */
      title: string;
      /** @example Leadership development program */
      description?: string;
      /**
       * Format: date
       * @example "2024-04-01T00:00:00.000Z"
       */
      startDate: string;
      /**
       * Format: date
       * @example "2024-06-30T00:00:00.000Z"
       */
      endDate: string;
    };
    UpdateScheduleRequest: {
      title?: string;
      description?: string;
      /** Format: date */
      startDate?: string;
      /** Format: date */
      endDate?: string;
      status?: components["schemas"]["ScheduleStatus"];
    };
    CreateAllocationRequest: {
      /** Format: uuid */
      scheduleId: string;
      /** Format: uuid */
      trainerId: string;
      allocationType: components["schemas"]["AllocationType"];
      /** Format: date */
      startDate: string;
      /** Format: date */
      endDate: string;
      /** Format: float */
      hoursPerWeek?: number;
      notes?: string;
    };
    UserListResponse: {
      data: components["schemas"]["User"][];
      meta: components["schemas"]["PaginationMeta"];
    };
    ScheduleListResponse: {
      data: components["schemas"]["Schedule"][];
      meta: components["schemas"]["PaginationMeta"];
    };
    AllocationListResponse: {
      data: components["schemas"]["TrainerAllocation"][];
      meta: components["schemas"]["PaginationMeta"];
    };
    AuditLogListResponse: {
      data: components["schemas"]["AuditLog"][];
      meta: components["schemas"]["PaginationMeta"];
    };
    Error: {
      /**
       * @description Human-readable error message
       * @example Invalid request parameters
       */
      message: string;
      /**
       * @description HTTP status code
       * @example 400
       */
      statusCode: number;
      /**
       * @description Field-specific validation errors
       * @example {
       *   "email": [
       *     "Email is required",
       *     "Email must be valid"
       *   ]
       * }
       */
      errors?: {
        [key: string]: string[];
      };
    };
    BadRequestError: components["schemas"]["Error"] & {
      /** @example 400 */
      statusCode?: unknown;
    };
    UnauthorizedError: components["schemas"]["Error"] & {
      /** @example 401 */
      statusCode?: unknown;
      /** @example Authentication required */
      message?: unknown;
    };
    ForbiddenError: components["schemas"]["Error"] & {
      /** @example 403 */
      statusCode?: unknown;
      /** @example Insufficient permissions */
      message?: unknown;
    };
    NotFoundError: components["schemas"]["Error"] & {
      /** @example 404 */
      statusCode?: unknown;
      /** @example Resource not found */
      message?: unknown;
    };
    ConflictError: components["schemas"]["Error"] & {
      /** @example 409 */
      statusCode?: unknown;
      /** @example Resource already exists */
      message?: unknown;
    };
    InternalServerError: components["schemas"]["Error"] & {
      /** @example 500 */
      statusCode?: unknown;
      /** @example Internal server error */
      message?: unknown;
    };
    PaginationMeta: {
      /**
       * @description Total number of items
       * @example 100
       */
      total: number;
      /**
       * @description Current page number (1-indexed)
       * @example 1
       */
      page: number;
      /**
       * @description Number of items per page
       * @example 20
       */
      pageSize: number;
      /**
       * @description Total number of pages
       * @example 5
       */
      totalPages: number;
    };
  };
  responses: {
    /** @description Bad request - invalid parameters */
    BadRequest: {
      content: {
        "application/json": components["schemas"]["BadRequestError"];
      };
    };
    /** @description Unauthorized - authentication required */
    Unauthorized: {
      content: {
        "application/json": components["schemas"]["UnauthorizedError"];
      };
    };
    /** @description Forbidden - insufficient permissions */
    Forbidden: {
      content: {
        "application/json": components["schemas"]["ForbiddenError"];
      };
    };
    /** @description Not found - resource does not exist */
    NotFound: {
      content: {
        "application/json": components["schemas"]["NotFoundError"];
      };
    };
    /** @description Conflict - resource already exists */
    Conflict: {
      content: {
        "application/json": components["schemas"]["ConflictError"];
      };
    };
    /** @description Internal server error */
    InternalServerError: {
      content: {
        "application/json": components["schemas"]["InternalServerError"];
      };
    };
  };
  parameters: {
    /** @description Page number (1-indexed) */
    PageParam?: number;
    /** @description Number of items per page */
    PageSizeParam?: number;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
